### PR TITLE
Addition of documentation, updates, and tutorial

### PR DESCRIPTION
**Pull request by vsoch**
This is a pull request to address the following issues:

 - #7 : I've added a changelog to keep track of chunks of changes, and dates. There aren't official tags or releases anywhere, so we can use this casual method until otherwise warranted.
 - #3 Per discussion, I've added the MIT license under @raphtown.
 - #4 I've added a CONTRIBUTORS.md and CONTRIBUTING.md doc to the root of the repo, and instructions in the README for contributing.
 - #6 This is a check for the jobname already running, which is important so that querying for it doesn't return more than one node. We instruct the user to end first, or resume.
 
The tutorial that I'd like to share (and please comment for review as well!) is here:

https://vsoch.github.io/lessons/sherlock-jupyter/

and when the changes and tutorial are reviewed, merged, I'll post / share for the larger sherlock community. I'd like to again emphasize how great (and happy this makes me!) to work on this together, and create as a resource for others to use! Let's do a really good job and have this sharing be more common :)

### CODE REVIEW

**Comment by raphtown** [comment]
Hey vsoch,

Thank you so much for this PR!  I unfortunately am going to be out for a while starting tomorrow, so I am adding my labmate @Eigenstate who might have the time to properly review and merge this in.  

I am excited that the community is responding so positively to this utility and look forward to refining it further!

**Comment by vsoch** [comment]
hey @raphtown ! It should be mostly ready to go (I tested everything so it's a quick review of the tutorial and changes to the soft parts of this repo) but definitely can wait if needed (I'm excited to get it out soon!) 

I'm traveling too, so to both of us, bon voyage!

**Comment by Eigenstate** [comment]
LGTM. Thanks for the contributions!

**Comment by vsoch** [comment]
Woohoo! Thanks everyone for the hard (and fun) work on this! If you ever want help toolizing something again (or adding features to an existing tool) please send me a note!

**Pull request merged**
